<main role="main" class="container mt-5">
  <div class="jumbotron">
    <h1>Server Side Include</h1>
    <p class="lead text-justify">
    	Lorem ipsum dolor sit amet, consectetur adipisicing elit. Consequatur expedita ipsum quam dolorum, mollitia nam laborum dignissimos! Omnis voluptatibus tempora consequuntur porro facere animi illum libero deserunt laboriosam dignissimos minus ducimus, modi distinctio veniam perspiciatis, fugiat! Minus sit tenetur ab quibusdam? Maxime doloribus, mollitia et fugit excepturi sed, deleniti eum nesciunt in doloremque sint dolorum, asperiores omnis quos aliquam delectus laboriosam harum distinctio repellendus praesentium. Eius, tenetur aspernatur sapiente, blanditiis aut aperiam ducimus laboriosam possimus doloribus soluta repudiandae adipisci porro inventore pariatur voluptatum, facilis maxime reprehenderit maiores quidem. Expedita dicta autem veritatis similique excepturi, vitae totam ipsa porro cupiditate alias.
    </p>
    <a class="btn btn-lg btn-primary" href="/docs/4.3/components/navbar/" role="button">Ver &raquo;</a>
  </div>
</main>